#!/usr/bin/env bash
set -euo pipefail

# Generate .github/workflows/build.yml from the package sources.
#
# GitHub Actions cannot derive job structure at run time, so the per-node build
# pipeline is generated offline and committed. The pipeline is
#
#   pkgs/ --(glbx graph)--> graph JSON --(jq)--> build.yml
#
# run end to end here: glbx reads the sources and emits the deterministic graph,
# jq turns it into one job per node. Nothing in between is stored — build.yml is
# the only committed derived artefact, and the check-graph CI job regenerates it
# from the current sources and fails the run if it has drifted.
#
# The generated file is thin: all build logic lives in hand-authored reusable
# workflows (.github/workflows/{build-glbx,check-graph,restore-inputs,plan,
# build-node}.yml). Only the graph-shaped wiring is generated — one caller job
# per node that `uses:` build-node.yml, carrying the node's needs: edges and the
# already-built skip guard, which are structural and so must stay in the
# committed file for check-graph to validate.
#
# One graph node becomes one job: it builds exactly that node with recursion
# inhibited (every dependency must already be a cache hit from an earlier job's
# publish) and then publishes that node to ghcr. Graph edges become job needs:.
#
# Usage: .github/generate-workflow.sh [output-yml]
#   output-yml  default .github/workflows/build.yml
# Environment:
#   GLBX   path to the glbx binary          (default: glbx on PATH)
#   STUB   path to the exec_env_stub binary (default: exec_env_stub on PATH)
#   ARCH   target architecture              (default: amd64)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="${1:-$SCRIPT_DIR/workflows/build.yml}"

GLBX="${GLBX:-glbx}"
STUB="${STUB:-exec_env_stub}"
ARCH="${ARCH:-amd64}"

mkdir -p "$(dirname "$OUT")"

{
	# Static header and the preamble jobs, each a thin caller of a reusable
	# workflow. A quoted heredoc delimiter keeps ${{ ... }} GitHub expressions
	# literal — the shell must not touch them.
	cat <<'EOF'
# Generated by .github/generate-workflow.sh from the package sources.
# Do not edit by hand: edit the sources, regenerate, and commit. The
# check-graph job fails the run if this file is stale.
name: build

on:
  workflow_dispatch:
    inputs:
      glbx-ref:
        description: glbx ref (branch, tag, or full SHA) to build the executor from
        default: main
        type: string
  push:

permissions:
  contents: read
  packages: write

jobs:

  build-glbx:
    uses: ./.github/workflows/build-glbx.yml
    with:
      glbx-ref: ${{ inputs.glbx-ref || 'main' }}

  check-graph:
    needs: [build-glbx]
    uses: ./.github/workflows/check-graph.yml

  restore-inputs:
    needs: [build-glbx]
    uses: ./.github/workflows/restore-inputs.yml
    with:
      arch: amd64

  plan:
    needs: [build-glbx, check-graph]
    uses: ./.github/workflows/plan.yml
    with:
      arch: amd64
EOF

	# One caller job per graph node. glbx emits the graph; jq turns it into YAML
	# in a single pass: node index becomes a stable, GHA-safe job id, the Key
	# rides in the job name and the node-key input (so the UI stays legible and
	# build-node gets the exact Key), and each node's incoming edges become
	# needs: on the predecessor jobs. The build logic itself is in build-node.yml;
	# the needs: edges and the if: skip guard stay here because they are
	# structural — they are exactly what check-graph validates.
	"$GLBX" graph --format=json --conf-dir "$CONF_DIR" --stub "$STUB" --arch "$ARCH" 2>/dev/null \
		| jq -r --arg q "'" '
			(.nodes | to_entries | map({(.value): .key}) | add) as $id
			| .edges as $edges
			| .nodes
			| to_entries[]
			| .key as $i
			| .value as $key
			| ([$edges[] | select(.to == $key) | $id[.from]] | sort) as $preds
			| (["build-glbx", "check-graph", "restore-inputs", "plan"] + ($preds | map("node-\(.)"))) as $needs
			| "
  node-\($i):
    name: \"\($key)\"
    needs: [\($needs | join(", "))]
    # Build unless this node is already present in the registry. A skipped
    # (already-built) dependency must not cascade-skip a dependent that does
    # need rebuilding, so !cancelled() && !failure() replaces the implicit
    # success() gate — which treats a skipped need as reason to skip. The skip
    # fires only on an explicit true: an empty plan output or a missing key
    # builds, so anything unexpected errs toward building.
    if: \"${{ !cancelled() && !failure() && (needs.plan.outputs.built == \($q)\($q) || fromJSON(needs.plan.outputs.built)[\($q)\($key)\($q)] != true) }}\"
    uses: ./.github/workflows/build-node.yml
    with:
      node-key: \"\($key)\"
      arch: amd64"
		'
} >"$OUT"

echo "wrote $OUT ($(wc -l <"$OUT") lines)"
