#!/usr/bin/env bash
set -euo pipefail

# Generate .github/workflows/build.yml from the package sources.
#
# GitHub Actions cannot derive job structure at run time, so the per-node build
# pipeline is generated offline and committed. The pipeline is
#
#   pkgs/ --(glbx graph)--> graph JSON --(jq)--> build.yml
#
# run end to end here: glbx reads the sources and emits the deterministic graph,
# jq turns it into one job per node. Nothing in between is stored — build.yml is
# the only committed derived artefact, and the check-graph CI job regenerates it
# from the current sources and fails the run if it has drifted.
#
# One graph node becomes one job: it builds exactly that node with recursion
# inhibited (every dependency must already be a cache hit from an earlier job's
# publish) and then publishes that node to ghcr. Graph edges become job needs:.
#
# Usage: .github/generate-workflow.sh [output-yml]
#   output-yml  default .github/workflows/build.yml
# Environment:
#   GLBX   path to the glbx binary          (default: glbx on PATH)
#   STUB   path to the exec_env_stub binary (default: exec_env_stub on PATH)
#   ARCH   target architecture              (default: amd64)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="${1:-$SCRIPT_DIR/workflows/build.yml}"

GLBX="${GLBX:-glbx}"
STUB="${STUB:-exec_env_stub}"
ARCH="${ARCH:-amd64}"

mkdir -p "$(dirname "$OUT")"

{
	# Static header and the two preamble jobs. A quoted heredoc delimiter keeps
	# ${{ ... }} GitHub expressions literal — the shell must not touch them.
	cat <<'EOF'
# Generated by .github/generate-workflow.sh from the package sources.
# Do not edit by hand: edit the sources, regenerate, and commit. The
# check-graph job fails the run if this file is stale.
name: build

on:
  workflow_dispatch:
    inputs:
      glbx-ref:
        description: glbx ref (branch, tag, or full SHA) to build the executor from
        default: main
        type: string
  push:

permissions:
  contents: read
  packages: write

env:
  GLBX_ARCH: amd64
  # ghcr.io/<owner>/<repo>/objstore — the shared pull-through cache and the only
  # channel between node jobs. Resolved from the run's own repository.
  GLBX_REGISTRY: ghcr.io/${{ github.repository }}/objstore
  # Credentials glbx redeems a registry bearer token with. The automatic
  # GITHUB_TOKEN has push access to the repository's own package namespace.
  GLBX_REGISTRY_USER: ${{ github.actor }}
  GLBX_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build-glbx:
    runs-on: ubuntu-latest
    steps:
      - name: Check out glbx
        uses: actions/checkout@v4
        with:
          repository: gardenlinux/glbx
          ref: ${{ inputs.glbx-ref || 'main' }}
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build glbx and the sandbox stub
        run: |
          go build -o bin/glbx ./cmd/glbx
          go build -o bin/exec_env_stub ./cmd/exec_env_stub
      - name: Share the binaries with the node jobs
        uses: actions/upload-artifact@v4
        with:
          name: glbx-bin-${{ github.run_id }}
          path: bin/
          retention-days: 1

  check-graph:
    runs-on: ubuntu-latest
    needs: [build-glbx]
    steps:
      - name: Check out the config repo
        uses: actions/checkout@v4
      - name: Fetch the glbx binaries
        uses: actions/download-artifact@v4
        with:
          name: glbx-bin-${{ github.run_id }}
          path: bin
      - run: chmod +x bin/glbx bin/exec_env_stub
      - name: Regenerate the workflow from the current sources and compare
        env:
          GLBX: bin/glbx
          STUB: bin/exec_env_stub
        run: |
          .github/generate-workflow.sh /tmp/build.current.yml
          if ! diff -u .github/workflows/build.yml /tmp/build.current.yml; then
            echo '::error::committed .github/workflows/build.yml is stale; run .github/generate-workflow.sh and commit'
            exit 1
          fi

  restore-inputs:
    runs-on: ubuntu-latest
    needs: [build-glbx]
    steps:
      - name: Check out the config repo
        uses: actions/checkout@v4
      - name: Fetch the glbx binaries
        uses: actions/download-artifact@v4
        with:
          name: glbx-bin-${{ github.run_id }}
          path: bin
      - run: chmod +x bin/glbx bin/exec_env_stub
      - name: Download the recorded inputs (source archives and tooling .debs)
        run: bin/glbx restore-cache --conf-dir . --arch "$GLBX_ARCH"
      - name: Publish the inputs to ghcr for the node jobs to pull
        run: bin/glbx publish --conf-dir . --stub bin/exec_env_stub --arch "$GLBX_ARCH"
EOF

	# One job per graph node. glbx emits the graph; jq turns it into YAML in a
	# single pass: node index becomes a stable, GHA-safe job id, the Key rides in
	# the job name and env (so the UI stays legible and --target gets the exact
	# Key), and each node's incoming edges become needs: on the predecessor jobs.
	"$GLBX" graph --format=json --conf-dir "$CONF_DIR" --stub "$STUB" --arch "$ARCH" 2>/dev/null \
		| jq -r '
			(.nodes | to_entries | map({(.value): .key}) | add) as $id
			| .edges as $edges
			| .nodes
			| to_entries[]
			| .key as $i
			| .value as $key
			| ([$edges[] | select(.to == $key) | $id[.from]] | sort) as $preds
			| (["build-glbx", "check-graph", "restore-inputs"] + ($preds | map("node-\(.)"))) as $needs
			| "
  node-\($i):
    name: \"\($key)\"
    runs-on: ubuntu-latest
    needs: [\($needs | join(", "))]
    env:
      NODE_KEY: \"\($key)\"
    steps:
      - name: Check out the config repo
        uses: actions/checkout@v4
      - name: Fetch the glbx binaries
        uses: actions/download-artifact@v4
        with:
          name: glbx-bin-${{ github.run_id }}
          path: bin
      - run: chmod +x bin/glbx bin/exec_env_stub
      - name: Build this node (dependencies must be cache hits)
        run: |
          bin/glbx build --target \"$NODE_KEY\" --no-recurse --stream \\
            --conf-dir . --stub bin/exec_env_stub --arch \"$GLBX_ARCH\"
      - name: Publish this node to ghcr
        run: |
          bin/glbx publish --target \"$NODE_KEY\" \\
            --conf-dir . --stub bin/exec_env_stub --arch \"$GLBX_ARCH\""
		'
} >"$OUT"

echo "wrote $OUT ($(wc -l <"$OUT") lines)"
