sources:
    - file: libmd_1.3.0.orig.tar.xz
      sha256: fc0f1eb6b6766470326f2c014693809190e67dba84274a6fbae9d4912d066706
      urls:
        - https://deb.debian.org/debian/pool/main/libm/libmd/libmd_1.3.0.orig.tar.xz
        - https://snapshot.debian.org/file/7626a8797ccb4954807f862bcfcdc7c67eaa58dd/libmd_1.3.0.orig.tar.xz
