#!/bin/sh

set -e

# If $DPKG_ROOT is set and not empty (this happens if dpkg is run with
# --force-script-chrootless) let pam-auth-update operate on a different
# directory by passing the --root parameter.
# Passing the root parameter is no longer needed if pam-auth-update
# switches to $DPKG_ROOT as the default for --root. See #1137186.
pam-auth-update ${DPKG_ROOT:+--root "$DPKG_ROOT"} --package

#DEBHELPER#
